---
start_date: 2019-08-01
tracker:
  timeout: 5h
monitor:
  polling_interval: 1m
sources:
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: annotation
  target: tmp_ndt.annotation
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: ndt7
  target: tmp_ndt.ndt7
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: ndt5
  target: tmp_ndt.ndt5
