---
start_date: 2020-01-01
tracker:
  timeout: 5h
monitor:
  polling_interval: 5m
sources:
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: ndt5
  target: tmp_ndt.ndt5
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: ndt7
  target: tmp_ndt.ndt7
- bucket: archive-measurement-lab
  experiment: ndt
  datatype: annotation
  target: tmp_ndt.annotation
